const a = {
  code: 0,
  data: {
    accessToken:
      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGaU1DUm5rSDVGSSttN3NPS0dRQUo4VzQ0WXZkQ2xjNGtGeDFONVdDTzJTZEhoSCtrUEx2M1hSeGkwUklkSzh6NEJhcHF1L3Njc09YN09PWUNpRVhKaU5JdVRsYnVoSWpYM2JjQUNqSTJoOD0iLCJleHAiOjE2OTUyODc5MjUsImlhdCI6MTY5NTI4NzMyNX0.YhkoEeql9ICzYle3hTvaR_O4VsXW3pLU5bjhRBrlfLw',
    expiredTime: 1695287925266,
    userName: 'secadmin',
  },
  message: '操作成功',
};

const b = {
  code: 0,
  message: '操作成功',
  data: {
    id: '1515887209228607488',
    uid: null,
    userName: 'secadmin',
    mobile: '13900667855',
    email: null,
    wkno: null,
    realName: '安全管理员',
    nickName: 'secadmin',
    avatar: '16853',
    brief: null,
    regionCode: null,
    region: null,
    changePasswordAgain: 0,
    lastUpdatePasswordTime: null,
    type: 1,
    loginSuccessTime: '2023-09-21 17:08:45',
    lastLoginTime: '2023-09-21 16:37:00',
    lastLoginIp: '172.18.1.67',
    enabled: true,
    loginFailLocked: false,
    roleInfo: [
      {
        userId: '1515887209228607488',
        roleCode: '103',
        roleId: '1515872054474252289',
        roleName: '安全管理员',
        platformCode: 'security',
      },
    ],
    orgInfo: [
      {
        userId: '1515887209228607488',
        orgId: '1524346394039595010',
        orgCode: '101',
        orgName: '默认组织',
      },
    ],
    userType: 'System',
    loginTips: null,
    platformInfo: {
      code: 'security',
      name: '安全平台',
      fullName: '安全管理平台',
      description: null,
    },
    passwordLevel: null,
    passwordRegex: null,
    checkPasswordMessage: null,
  },
};

const c = {
  code: 0,
  message: '操作成功',
  data: [
    'plugin.software.download',
    'plugin.software.plugin',
    'plugin.software',
    'zcgl.source.database.test',
    'zcgl.source.database.update',
    'zcgl.source.database.list',
    'zcgl.source.database.add',
    'zcgl.source.database.import',
    'zcgl.source.database.delete',
    'zcgl.source.database.export',
    'zcgl.source.database',
    'zcgl.scan.add.detail.directly',
    'zcgl.scan.add.detail',
    'zcgl.scan.stop',
    'zcgl.scan.start',
    'zcgl.scan.add',
    'zcgl.scan.delete',
    'zcgl.scan.detail',
    'zcgl.scan.list',
    'zcgl.scan',
    'zcgl',
    'mgfx.sensitive.scan.get.result',
    'mgfx.sensitive.scan.update',
    'mgfx.sensitive.scan.list',
    'mgfx.sensitive.scan.update.result',
    'mgfx.sensitive.scan.add',
    'mgfx.sensitive.scan.add.result',
    'mgfx.sensitive.scan.pauseOrStop',
    'mgfx.sensitive.scan.delete',
    'mgfx.sensitive.scan.start',
    'mgfx.sensitive.scan',
    'mgfx.sensitive.config.list',
    'mgfx.sensitive.config.add',
    'mgfx.sensitive.config.update',
    'mgfx.sensitive.config.update.field',
    'mgfx.sensitive.config.delete.field',
    'mgfx.sensitive.config.importSensitiveConfig',
    'mgfx.sensitive.config.exportSensitiveConfig',
    'mgfx.sensitive.config.delete',
    'mgfx.sensitive.config.classification',
    'mgfx.sensitive.config',
    'mgfx',
    'jmgl.encryption.list',
    'jmgl.encryption.sourceDatabase',
    'jmgl.encryption.database',
    'jmgl.encryption.schema',
    'jmgl.encryption.table',
    'jmgl.encryption.field',
    'jmgl.encryption.encAlgorithm',
    'jmgl.encryption.addTable',
    'jmgl.encryption.editTable',
    'jmgl.encryption.delete',
    'jmgl.encryption.get',
    'jmgl.encryption.getField',
    'jmgl.encryption.getResult',
    'jmgl.encryption.getTableData',
    'jmgl.encryption.start',
    'jmgl.encryption.encKeySource',
    'jmgl.encryption.test',
    'jmgl.encryption',
    'jmgl.decryption.list',
    'jmgl.decryption.sourceDatabase',
    'jmgl.decryption.database',
    'jmgl.decryption.schema',
    'jmgl.decryption.table',
    'jmgl.decryption.field',
    'jmgl.decryption.encAlgorithm',
    'jmgl.decryption.addTable',
    'jmgl.decryption.editTable',
    'jmgl.decryption.delete',
    'jmgl.decryption.get',
    'jmgl.decryption.getField',
    'jmgl.decryption.getResult',
    'jmgl.decryption.getTableData',
    'jmgl.decryption.start',
    'jmgl.decryption.encKeySource',
    'jmgl.decryption.test',
    'jmgl.decryption',
    'jmgl',
    'mygl.key.management.list',
    'mygl.key.management.list.detail',
    'mygl.key.management',
    'mygl.encryption.back.update',
    'mygl.encryption.back.add',
    'mygl.encryption.back.recordList',
    'mygl.encryption.back.list',
    'mygl.encryption.back.download',
    'mygl.encryption.back.get',
    'mygl.encryption.back.details',
    'mygl.encryption.back',
    'mygl.encryption.roll.list',
    'mygl.encryption.roll.upload',
    'mygl.encryption.roll.get',
    'mygl.encryption.roll.update',
    'mygl.encryption.roll.key.list',
    'mygl.encryption.roll',
    'mygl',
    'access.blackAndWhite.list',
    'access.blackAndWhite.delete',
    'access.blackAndWhite.add',
    'access.blackAndWhite.update',
    'access.blackAndWhite',
    'access.proxy.update',
    'access.proxy.get',
    'access.proxy.add',
    'access.proxy.delete',
    'access.proxy.state',
    'access.proxy.list',
    'access.proxy.listNetworkInfo',
    'access.proxy',
    'access',
    'pzgl.dict.add',
    'pzgl.dict.detail.get',
    'pzgl.dict.detail.delete',
    'pzgl.dict.update',
    'pzgl.dict.delete',
    'pzgl.dict.detail.add',
    'pzgl.dict.list',
    'pzgl.dict',
    'pzgl.regex.add',
    'pzgl.regex.update',
    'pzgl.regex.delete',
    'pzgl.regex.list',
    'pzgl.regex',
    'pzgl.sensitive.type.add',
    'pzgl.sensitive.type.update',
    'pzgl.sensitive.type.list',
    'pzgl.sensitive.type.delete',
    'pzgl.sensitive.type',
    'pzgl',
  ],
};
